server.port=8761
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

eureka.instance.leaseRenewalIntervalInSeconds=30
eureka.client.registryFetchIntervalSeconds=30

spring.application.name=gateway-service
